<script setup lang="ts">
/**
 * Inline stat derived from src/wasm/meta.json (regenerated by `yarn copy:wasm`).
 * Keeps doc prose in sync with the actual shipped WASM build.
 */
import { computed } from 'vue'
import wasmMeta from '@/wasm/meta.json'

const props = defineProps<{
  /** Which stat to render */
  type: 'version' | 'size' | 'gzip' | 'js'
}>()

const text = computed(() => {
  switch (props.type) {
    case 'version':
      return `v${wasmMeta.version}`
    case 'size':
      return `${wasmMeta.sizeKB}KB`
    case 'gzip':
      return `${wasmMeta.gzipKB}KB`
    case 'js':
      return `${wasmMeta.jsKB}KB`
  }
})
</script>

<template>
  <span>{{ text }}</span>
</template>
